apiVersion: v1
kind: Pod

metadata:
  name: notas-api
  namespace: notas
  labels:
    app: notas-api

spec:
  containers:
    - name: notas-api
      image: notas-api
      imagePullPolicy: Never

      ports:
        - containerPort: 8000

      env:
        - name: NOTES_FILE
          value: /data/notes.json

      volumeMounts:
        - name: notas-storage
          mountPath: /data

  volumes:
    - name: notas-storage
      persistentVolumeClaim:
        claimName: notas-pvc